# Assignemnt 2


In [ ]:
# pip install opencv-python

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/39.0 MB ? eta -:--:--
    --------------------------------------- 0.5/39.0 MB 4.0 MB/s eta 0:00:10
   - -------------------------------------- 1.3/39.0 MB 3.9 MB/s eta 0:00:10
   -- ------------------------------------- 2.1/39.0 MB 3.9 MB/s eta 0:00:10
   -- ------------------------------------- 2.9/39.0 MB 3.9 MB/s eta 0:00:10
   --- ------------------------------------ 3.7/39.0 MB 3.9 MB/s eta 0:00:09
   ---- ----------------------------------- 4.5/39.0 MB 3.9 MB/s eta 0:00:09
   ----- ---------------------------------- 5.5/39.0 MB 3.9 MB/s eta 0:00:09
   ------ --------------------------------- 6.3/39.0 MB 3.9 MB/s eta 0:00:09
   ------- -------------------------------- 7.1/39.0 MB 3.9 MB/s eta 0:00:09
   -------- ------------------------------- 7.9/39.0 MB 3.9 MB/s eta 0:00:09
   -------- ------------------------------- 8.7/39.0 MB 3.9 MB/s eta 0:00:08
   --

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.61.0 requires numpy<2.2,>=1.24, but you have numpy 2.2.6 which is incompatible.
streamlit 1.45.1 requires packaging<25,>=20, but you have packaging 25.0 which is incompatible.

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
import cv2
import os
import numpy as np

def one_hot_encoding(img_true_classes, num_of_classes):
    num_of_images = img_true_classes.shape[0]
    one_hot_encoded_matrix = np.zeros((num_of_images, num_of_classes))
    one_hot_encoded_matrix[np.arange(num_of_images), img_true_classes] = 1

    return one_hot_encoded_matrix

def load_dataset(data_dir, img_size = 64):
    features = []
    labels = []

    classes_names = [entry.name for entry in os.scandir(data_dir) if entry.is_dir()]
    classes_names = sorted(classes_names)

    for class_index, class_name in enumerate(classes_names):
        class_path = os.path.join(data_dir,class_name)
        print(f"Loading Class {class_index}: {class_name}")

        for img_name in os.listdir(class_path):
            img_path = os.path.join(class_path, img_name)
            
            try:
                img_np_arr = cv2.imread(img_path)

                if img_np_arr is None:
                    continue
                
                img_resized_arr = cv2.resize(img_np_arr, (img_size,img_size))
                img_flatten_arr = img_resized_arr.flatten()
                features.append(img_flatten_arr)
                labels.append(class_index)

            except Exception as e:
                print(f"Error loading {img_name}: {e}")


    X = np.array(features)
    y = np.array(labels)

    X = X/255
    y = one_hot_encoding(y, len(classes_names))

    return X, y, classes_names



img_features, img_true_values, classes_names = load_dataset(r"C:\Life\FCAI_Stuff\Third_year_AI\Intro_to_ML\Assignments\Sea_Animals")
print(img_features)
print(img_true_values)

    

Loading Class 0: Clams
Loading Class 1: Corals
Loading Class 2: Crabs
Loading Class 3: Dolphin
Loading Class 4: Eel
Loading Class 5: Fish
Loading Class 6: Jelly_Fish
Loading Class 7: Lobster
Loading Class 8: Nudibranchs
Loading Class 9: Octopus
Loading Class 10: Otter
Loading Class 11: Penguin
Loading Class 12: Puffers
Loading Class 13: Sea_Rays
Loading Class 14: Sea_Urchins
Loading Class 15: Seahorse
Loading Class 16: Seal
Loading Class 17: Sharks
Loading Class 18: Shrimp
Loading Class 19: Squid
Loading Class 20: Starfish
Loading Class 21: Turtle_Tortoise
Loading Class 22: Whale
[[0.34117647 0.36078431 0.23137255 ... 0.54901961 0.74901961 0.63529412]
 [0.41568627 0.41176471 0.43529412 ... 0.41568627 0.38823529 0.26666667]
 [0.36078431 0.38431373 0.25490196 ... 0.92156863 0.89019608 0.64705882]
 ...
 [0.74901961 0.50980392 0.37647059 ... 0.7372549  0.4627451  0.31764706]
 [0.6745098  0.50196078 0.36470588 ... 0.25882353 0.23529412 0.14509804]
 [0.93333333 0.78039216 0.65490196 ... 0.85

[[0.34117647 0.36078431 0.23137255 ... 0.54901961 0.74901961 0.63529412]
 [0.41568627 0.41176471 0.43529412 ... 0.41568627 0.38823529 0.26666667]
 [0.36078431 0.38431373 0.25490196 ... 0.92156863 0.89019608 0.64705882]
 ...
 [0.74901961 0.50980392 0.37647059 ... 0.7372549  0.4627451  0.31764706]
 [0.6745098  0.50196078 0.36470588 ... 0.25882353 0.23529412 0.14509804]
 [0.93333333 0.78039216 0.65490196 ... 0.85490196 0.70980392 0.61568627]]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
